services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    environment:
      # IMPORTANT: keep localhost here so the browser can reach the API
      - PUBLIC_API_BASE=http://localhost:8000
      - NPM_CONFIG_OPTIONAL=true
      - NPM_CONFIG_AUDIT=false
      - NPM_CONFIG_FUND=false
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
      - frontend_npm_cache:/root/.npm
    command: >
      sh -lc "
        (npm ci || (rm -rf node_modules && npm install)) &&
        npm run dev -- --host 0.0.0.0
      "

volumes:
  frontend_node_modules:
  frontend_npm_cache:
