services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    environment:
      # IMPORTANT: keep localhost here so the browser can reach the API
      - PUBLIC_API_BASE=http://localhost:8000
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
    command: sh -lc "npm install --no-audit --no-fund && npm run dev -- --host 0.0.0.0"

volumes:
  frontend_node_modules:
