project:
  type: website
  output-dir: ../docs/site/
  render:
    - "*.qmd"
    - "*.ipynb"

date: last-modified

website:
  title: "Digitization Toolkit Documentation"
  sidebar:
    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - href: index.qmd
        text: Home
      - section: "Developer Guides"
        contents:
          - section: "Hardware Setup Guides"
            contents:
              - href: developers/device_setup_CM4.qmd
                text: "Device Setup: Raspberry Pi CM4 with Cameras"
              - href: developers/device_setup_pi5_imx519.qmd
                text: "Device Setup: Raspberry Pi 5 with IMX519 Camera"
  page-footer:
    center: "Documentation site built: {{< meta date >}} | [View on GitHub](https://github.com/UCSB-AMPLab/digitization-toolkit-software)"

format:
  html:
    css: _static/css/project.scss
    theme: cosmo
    toc: true
